// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: AboutProject

#ifndef _ABOUTPROJECT_UI_H
#define _ABOUTPROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"
#include "PageManager.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////
#include "ui_AboutPage.h"
#include "ui_MeunPage.h"
#include "ui_HomePage.h"
#include "ui_MotorPage.h"
#include "ui_LightPage.h"      
#include "ui_CalendarPage.h"  
///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;


// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1118704736);    // assets/屏幕截图 2026-06-07 172226.png

// FONTS
// From AboutProject
LV_FONT_DECLARE(ui_font_zhongyaun16);
LV_FONT_DECLARE(ui_font_zhongyaun20);

// From HomePage (Project)
LV_FONT_DECLARE(ui_font_zhongyuan100);
LV_FONT_DECLARE(ui_font_zhongyuan18);
LV_FONT_DECLARE(ui_font_zhongyuan20);
LV_FONT_DECLARE(ui_font_zhongyuan24);
LV_FONT_DECLARE(ui_font_zhongyuan30);
LV_FONT_DECLARE(ui_font_zhongyuan38);
LV_FONT_DECLARE(ui_font_zhongyuan48);
LV_FONT_DECLARE(ui_font_zhongyuan80);
LV_FONT_DECLARE(ui_font_Font40);

// From MeunProject
LV_FONT_DECLARE(ui_font_iconfont10);
LV_FONT_DECLARE(ui_font_iconfont20);
LV_FONT_DECLARE(ui_font_iconfont31);
LV_FONT_DECLARE(ui_font_iconfont40);
LV_FONT_DECLARE(ui_font_zhongyuan);
LV_FONT_DECLARE(ui_font_zhongyuan30);
LV_FONT_DECLARE(ui_font_zhongyuan40);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
