// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: AboutProject

#ifndef UI_ABOUTPAGE_H
#define UI_ABOUTPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "PageManager.h"  // 添加这一行

// SCREEN: ui_AboutPage
extern void ui_AboutPage_screen_init(void);
extern void ui_AboutPage_screen_destroy(void);
extern lv_obj_t * ui_AboutPage;
// extern lv_obj_t * ui_Label1;
// extern lv_obj_t * ui_Label2;
// extern lv_obj_t * ui_Label3;
// extern lv_obj_t * ui_Label4;
// extern lv_obj_t * ui_Label5;
// extern lv_obj_t * ui_Label6;
// extern lv_obj_t * ui_Label7;
// extern lv_obj_t * ui_Label8;
// extern lv_obj_t * ui_Label9;
// extern lv_obj_t * ui_Label10;
// extern lv_obj_t * ui_Label11;
// extern lv_obj_t * ui_Label12;
// extern lv_obj_t * ui_Label13;
// extern lv_obj_t * ui_Label14;
// extern lv_obj_t * ui_Label15;
// extern lv_obj_t * ui_Label16;
// extern lv_obj_t * ui_Label17;
// extern lv_obj_t * ui_Label18;

// CUSTOM VARIABLES
extern lv_obj_t * ui_AboutPage;
extern Page_t Page_About;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
