// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Project

#ifndef UI_CALENDARPAGE_H
#define UI_CALENDARPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "ui.h"

// SCREEN: ui_CalendarPage
extern void ui_CalendarPage_screen_init(void);
extern void ui_CalendarPage_screen_destroy(void);
extern lv_obj_t * ui_CalendarPage;
extern lv_obj_t * ui_Calendar1;
// CUSTOM VARIABLES
extern lv_obj_t * ui_CalendarPage;

extern Page_t Page_Calendar;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

