// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Project

#ifndef UI_HOMEPAGE_H
#define UI_HOMEPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "ui.h"
#include "PageManager.h"

// SCREEN: ui_HomePage
extern void ui_HomePage_screen_init(void);
extern void ui_HomePage_screen_destroy(void);
extern lv_obj_t * ui_HomePage;
// extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES
extern lv_obj_t * ui_HomePage;

extern Page_t Page_Home;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

