// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Project

#ifndef UI_LIGHTPAGE_H
#define UI_LIGHTPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "ui.h"

// SCREEN: ui_LightPage
extern void ui_LightPage_screen_init(void);
extern void ui_LightPage_screen_destroy(void);
extern lv_obj_t * ui_LightPage;
extern lv_obj_t * ui_RGBColor;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES
extern lv_obj_t * ui_LightPage;

extern Page_t Page_Light;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

