// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Project

#ifndef UI_MOTORPAGE_H
#define UI_MOTORPAGE_H

#ifdef __cplusplus
extern "C" {
#endif

#include "ui.h"
#include "PageManager.h"
// SCREEN: ui_MotorPage
extern void ui_MotorPage_screen_init(void);
extern void ui_MotorPage_screen_destroy(void);
extern lv_obj_t * ui_MotorPage;
extern lv_obj_t * ui_Arc1;
// extern lv_obj_t * ui_Label3;
// CUSTOM VARIABLES
extern lv_obj_t * ui_MotorPage;

extern Page_t Page_Motor;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

