// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: MeunProject

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

#include "ui.h"
#include "PageManager.h"

#define ABOUT_PAGE_EN			1
#define MOTOR_PAGE_EN			1
#define LIGHT_PAGE_EN			1
#define CALENDAR_PAGE_EN		1

// SCREEN: ui_Screen1
extern void ui_MeunPage_screen_init(void);
extern void ui_MeunPage_screen_destroy(void);
extern lv_obj_t * ui_MeunPage;
extern lv_obj_t * ui_MotorPanel;
extern lv_obj_t * ui_MotorButton;
extern lv_obj_t * ui_MotorLabel1;
extern lv_obj_t * ui_MotorLabel2;
extern lv_obj_t * ui_LightPanel;
extern lv_obj_t * ui_LightButton;
extern lv_obj_t * ui_LightLabel1;
extern lv_obj_t * ui_LightLabel2;
extern lv_obj_t * ui_CalenderPanel;
extern lv_obj_t * ui_CalenderButton;
extern lv_obj_t * ui_CalenderLabel1;
extern lv_obj_t * ui_CalenderLabel2;
extern lv_obj_t * ui_AboutPanel;
extern lv_obj_t * ui_AboutButton;
extern lv_obj_t * ui_AboutLabel1;
extern lv_obj_t * ui_AboutLabel2;
// CUSTOM VARIABLES
extern lv_obj_t * ui_MeunPage;
extern lv_obj_t * ui_MotorButton;

extern int16_t ui_MenuScrollY;

extern Page_t Page_Menu;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

