// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: AboutProject

#include "ui.h"
#include "ui_helpers.h"
#include "ui_AboutPage.h"
///////////////////// VARIABLES ////////////////////
lv_obj_t * ui_AboutPage = NULL;
/////////////////// Page Manager ////////////////////
Page_t Page_About = {
    .init = ui_AboutPage_screen_init,
    .deinit = ui_AboutPage_screen_destroy,
    .page = NULL
};

// lv_obj_t * ui_AboutPage;

static lv_obj_t * ui_Label1 = NULL;
static lv_obj_t * ui_Label2 = NULL;
static lv_obj_t * ui_Label3 = NULL;
static lv_obj_t * ui_Label4 = NULL;
static lv_obj_t * ui_Label5 = NULL;
static lv_obj_t * ui_Label6 = NULL;
static lv_obj_t * ui_Label7 = NULL;
static lv_obj_t * ui_Label8 = NULL;
static lv_obj_t * ui_Label9 = NULL;
static lv_obj_t * ui_Label10 = NULL;
static lv_obj_t * ui_Label11 = NULL;
static lv_obj_t * ui_Label12 = NULL;
static lv_obj_t * ui_Label13 = NULL;
static lv_obj_t * ui_Label14 = NULL;
static lv_obj_t * ui_Label15 = NULL;
static lv_obj_t * ui_Label16 = NULL;
static lv_obj_t * ui_Label17 = NULL;
static lv_obj_t * ui_Label18 = NULL;
// event funtions

// build funtions

void ui_AboutPage_screen_init(void)
{
    ui_AboutPage = lv_obj_create(NULL);

    lv_obj_set_scroll_dir(ui_AboutPage, LV_DIR_VER);

     lv_obj_set_style_bg_color(ui_AboutPage, lv_color_hex(0x000000), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_AboutPage, 255, LV_PART_MAIN);
    
    ui_Label1 = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 20);
    lv_obj_set_y(ui_Label1, -100);
    lv_obj_set_align(ui_Label1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label1, "设备名称");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x1980E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_zhongyaun20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 20);
    lv_obj_set_y(ui_Label2, -75);
    lv_obj_set_align(ui_Label2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label2, "智能中控屏");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_zhongyaun16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 20);
    lv_obj_set_y(ui_Label3, -50);
    lv_obj_set_align(ui_Label3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label3, "固件型号");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x1980E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &ui_font_zhongyaun20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 20);
    lv_obj_set_y(ui_Label4, -25);
    lv_obj_set_align(ui_Label4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label4, "V1.0.0");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_zhongyaun16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 20);
    lv_obj_set_y(ui_Label5, 0);
    lv_obj_set_align(ui_Label5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label5, "主控芯片");
    lv_obj_set_style_text_color(ui_Label5, lv_color_hex(0x1980E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label5, &ui_font_zhongyaun20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 20);
    lv_obj_set_y(ui_Label6, 25);
    lv_obj_set_align(ui_Label6, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label6, "STM32F407VET6");
    lv_obj_set_style_text_font(ui_Label6, &ui_font_zhongyaun16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 20);
    lv_obj_set_y(ui_Label7, 50);
    lv_obj_set_align(ui_Label7, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label7, "操作系统");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0x1980E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &ui_font_zhongyaun20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 20);
    lv_obj_set_y(ui_Label8, 75);
    lv_obj_set_align(ui_Label8, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label8, "FreeRTOS");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_zhongyaun16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 20);
    lv_obj_set_y(ui_Label9, 100);
    lv_obj_set_align(ui_Label9, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label9, "图形界面");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0x1980E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &ui_font_zhongyaun20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 20);
    lv_obj_set_y(ui_Label10, 125);
    lv_obj_set_align(ui_Label10, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label10, "LVGL");
    lv_obj_set_style_text_font(ui_Label10, &ui_font_zhongyaun16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, 20);
    lv_obj_set_y(ui_Label11, 150);
    lv_obj_set_align(ui_Label11, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label11, "硬件开发者");  //硬件开发者
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0x1980E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &ui_font_zhongyaun20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 20);
    lv_obj_set_y(ui_Label12, 175);
    lv_obj_set_align(ui_Label12, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label12, "廖明宇2320140003");
    lv_obj_set_style_text_font(ui_Label12, &ui_font_zhongyaun16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 20);
    lv_obj_set_y(ui_Label13, 200);
    lv_obj_set_align(ui_Label13, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label13, "BSP驱动开发者");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0x1980E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &ui_font_zhongyaun20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 20);
    lv_obj_set_y(ui_Label14, 225);
    lv_obj_set_align(ui_Label14, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label14, "廖明宇2320140003");
    lv_obj_set_style_text_font(ui_Label14, &ui_font_zhongyaun16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 20);
    lv_obj_set_y(ui_Label15, 250);
    lv_obj_set_align(ui_Label15, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label15, "界面设计者");
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0x1980E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &ui_font_zhongyaun20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 20);
    lv_obj_set_y(ui_Label16, 275);
    lv_obj_set_align(ui_Label16, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label16, "朱炫兆2320140023");
    lv_obj_set_style_text_font(ui_Label16, &ui_font_zhongyaun16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 20);
    lv_obj_set_y(ui_Label17, 300);
    lv_obj_set_align(ui_Label17, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label17, "系统任务开发者");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0x1980E1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &ui_font_zhongyaun20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_AboutPage);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 20);
    lv_obj_set_y(ui_Label18, 325);
    lv_obj_set_align(ui_Label18, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label18, "朱炫兆2320140023");
    lv_obj_set_style_text_font(ui_Label18, &ui_font_zhongyaun16, LV_PART_MAIN | LV_STATE_DEFAULT);

    Page_About.page = ui_AboutPage;
}

void ui_AboutPage_screen_destroy(void)
{
    //if(ui_AboutPage) lv_obj_del(ui_AboutPage);

    // NULL screen variables
    ui_AboutPage = NULL;
    ui_AboutPage = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;
    ui_Label3 = NULL;
    ui_Label4 = NULL;
    ui_Label5 = NULL;
    ui_Label6 = NULL;
    ui_Label7 = NULL;
    ui_Label8 = NULL;
    ui_Label9 = NULL;
    ui_Label10 = NULL;
    ui_Label11 = NULL;
    ui_Label12 = NULL;
    ui_Label13 = NULL;
    ui_Label14 = NULL;
    ui_Label15 = NULL;
    ui_Label16 = NULL;
    ui_Label17 = NULL;
    ui_Label18 = NULL;

}
