// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Project

#include "ui.h"
#include "ui_CalendarPage.h"

lv_obj_t * ui_CalendarPage;
lv_obj_t * ui_CalendarPage = NULL;
lv_obj_t * ui_Calendar1 = NULL;
// event funtions

/////////////////// Page Manager ////////////////////
Page_t Page_Calendar = {
    .init = ui_CalendarPage_screen_init,
    .deinit = ui_CalendarPage_screen_destroy,
    .page = NULL
};
// build funtions

void ui_CalendarPage_screen_init(void)
{
    ui_CalendarPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CalendarPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Calendar1 = lv_calendar_create(ui_CalendarPage);
    lv_obj_t * ui_Calendar1_header = lv_calendar_header_arrow_create(ui_Calendar1);
    lv_obj_set_width(ui_Calendar1, 320);
    lv_obj_set_height(ui_Calendar1, 240);
    lv_obj_set_align(ui_Calendar1, LV_ALIGN_CENTER);

    Page_Calendar.page = ui_CalendarPage;

}

void ui_CalendarPage_screen_destroy(void)
{
    //if(ui_CalendarPage) lv_obj_del(ui_CalendarPage);

    // NULL screen variables
    ui_CalendarPage = NULL;
    Page_Calendar.page = NULL;
    ui_Calendar1 = NULL;

}
