// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Project

#include "ui.h"
#include "ui_HomePage.h"
#include "user_TaskInit.h"

extern osMessageQueueId_t RTC_TimeQueue;
static RTC_Time_t current_time;

lv_obj_t * ui_HomePage = NULL;
lv_obj_t * ui_Image7 = NULL;
static lv_obj_t * ui_Label1 = NULL;
// event funtions
Page_t Page_Home = {
    .init = ui_HomePage_screen_init,
    .deinit = ui_HomePage_screen_destroy,
    .page = NULL
};
// build funtions

// 创建一个定时器或任务来更新UI
static void update_time_cb(lv_timer_t * timer)
{
    RTC_Time_t rtc_data;
    
    // 非阻塞接收
    if(osMessageQueueGet(RTC_TimeQueue, &rtc_data, NULL, 0) == osOK)
    {
        current_time = rtc_data;
        
        if(ui_Label1 != NULL)
        {
            char buf[16];
            sprintf(buf, "%02d:%02d:%02d", 
                    rtc_data.hours, rtc_data.minutes, rtc_data.seconds);
            lv_label_set_text(ui_Label1, buf);
        }
    }
}


void ui_HomePage_screen_init(void)
{
    ui_HomePage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomePage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_HomePage, &ui_font_zhongyuan18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_HomePage);
    lv_img_set_src(ui_Image7, &ui_img_1118704736);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 384
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 240
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);

    ui_Label1 = lv_label_create(ui_HomePage);
    lv_obj_set_width(ui_Label1, lv_pct(50));
    lv_obj_set_height(ui_Label1, lv_pct(33));
    lv_obj_set_x(ui_Label1, -106);
    lv_obj_set_y(ui_Label1, -74);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "00:00");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x4F4E55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_zhongyuan30, LV_PART_MAIN | LV_STATE_DEFAULT);

    Page_Home.page = ui_HomePage;

    // 创建定时器，每100ms检查一次队列
    lv_timer_create(update_time_cb, 100, NULL);
}

void ui_HomePage_screen_destroy(void)
{
    //if(ui_HomePage) lv_obj_del(ui_HomePage);

    // NULL screen variables
    ui_HomePage = NULL;
    ui_HomePage = NULL;
    ui_Label1 = NULL;

}
