// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Project

#include "ui.h"
#include "ui_LightPage.h"
#include "cmsis_os.h"
#include "user_TaskInit.h"
#include "RGB_Led.h"

lv_obj_t * ui_LightPage = NULL;
lv_obj_t * ui_RGBColor = NULL;
lv_obj_t * ui_Label2 = NULL;
static lv_obj_t * ui_color_label = NULL;  // 显示当前颜色名称
// event funtions
// 事件回调函数声明
static void colorwheel_event_cb(lv_event_t * e);
// RGB值到7种颜色的映射函数
static uint8_t map_rgb_to_7color(uint8_t r, uint8_t g, uint8_t b);
/////////////////// Page Manager ////////////////////
Page_t Page_Light = {
    .init = ui_LightPage_screen_init,
    .deinit = ui_LightPage_screen_destroy,
    .page = NULL
};

// build funtions

void ui_LightPage_screen_init(void)
{
    ui_LightPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LightPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RGBColor = lv_colorwheel_create(ui_LightPage, true);
    lv_obj_set_width(ui_RGBColor, 150);
    lv_obj_set_height(ui_RGBColor, 150);
    lv_obj_set_x(ui_RGBColor, -10);
    lv_obj_set_y(ui_RGBColor, -10);
    lv_obj_set_align(ui_RGBColor, LV_ALIGN_CENTER);

    // 添加事件回调：值变化时触发
    lv_obj_add_event_cb(ui_RGBColor, colorwheel_event_cb, LV_EVENT_VALUE_CHANGED, NULL);

    ui_Label2 = lv_label_create(ui_LightPage);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -13);
    lv_obj_set_y(ui_Label2, -102);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Light color");

    // 添加显示当前颜色的标签
    ui_color_label = lv_label_create(ui_LightPage);
    lv_obj_set_width(ui_color_label, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_color_label, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_color_label, 0);
    lv_obj_set_y(ui_color_label, 100);
    lv_obj_set_align(ui_color_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_color_label, "Color: Red");

    Page_Light.page = ui_LightPage;
}

void ui_LightPage_screen_destroy(void)
{
    //if(ui_LightPage) lv_obj_del(ui_LightPage);

    // NULL screen variables
    ui_LightPage = NULL;
    Page_Light.page = NULL;
    ui_RGBColor = NULL;
    ui_Label2 = NULL;
}

// RGB值到7种颜色的映射函数
static uint8_t map_rgb_to_7color(uint8_t r, uint8_t g, uint8_t b)
{
    // 判断白色（RGB都大于180）
    if(r > 180 && g > 180 && b > 180)
    {
        return color_white;
    }
    // 判断红色（R最强且R>G+B，或R>150且G<100且B<100）
    else if(r > 150 && g < 100 && b < 100)
    {
        return color_red;
    }
    // 判断绿色（G最强且G>R+B，或G>150且R<100且B<100）
    else if(g > 150 && r < 100 && b < 100)
    {
        return color_green;
    }
    // 判断蓝色（B最强且B>R+G，或B>150且R<100且G<100）
    else if(b > 150 && r < 100 && g < 100)
    {
        return color_blue;
    }
    // 判断黄色（R和G强，B弱）
    else if(r > 150 && g > 150 && b < 100)
    {
        return color_yellow;
    }
    // 判断紫色（R和B强，G弱）
    else if(r > 150 && b > 150 && g < 100)
    {
        return color_purple;
    }
    // 判断青色（G和B强，R弱）
    else if(g > 150 && b > 150 && r < 100)
    {
        return color_cyan;
    }
    
    // 默认返回红色
    return color_red;
}

// 颜色枚举转字符串
static const char* color_to_string(uint8_t color)
{
    switch(color)
    {
        case color_red:    return "Red";
        case color_green:  return "Green";
        case color_blue:   return "Blue";
        case color_yellow: return "Yellow";
        case color_purple: return "Purple";
        case color_cyan:   return "Cyan";
        case color_white:  return "White";
        default:           return "Unknown";
    }
}

// 色环事件回调函数
static void colorwheel_event_cb(lv_event_t * e)
{
    lv_obj_t * colorwheel = lv_event_get_target(e);
    
    // 获取当前选中的颜色（16位 RGB565 格式）
    lv_color_t color = lv_colorwheel_get_rgb(colorwheel);
    uint16_t rgb565 = color.full;
    
    // ========== 手动将RGB565转换为RGB888 ==========
    // RGB565格式: RRRRRGGG GGGBBBBB
    uint8_t r5 = (rgb565 >> 11) & 0x1F;   // 取高5位红色
    uint8_t g6 = (rgb565 >> 5) & 0x3F;    // 取中间6位绿色
    uint8_t b5 = rgb565 & 0x1F;           // 取低5位蓝色
    
    // 扩展到8位 (0-255)
    uint8_t red = (r5 * 255) / 31;
    uint8_t green = (g6 * 255) / 63;
    uint8_t blue = (b5 * 255) / 31;
    
    // ========== 根据RGB值判断对应的7种颜色 ==========
    uint8_t color_index;
    const char* color_name;
    
    // 判断白色
    if(red > 180 && green > 180 && blue > 180)
    {
        color_index = color_white;
        color_name = "White";
    }
    // 判断红色
    else if(red > 150 && green < 100 && blue < 100)
    {
        color_index = color_red;
        color_name = "Red";
    }
    // 判断绿色
    else if(green > 150 && red < 100 && blue < 100)
    {
        color_index = color_green;
        color_name = "Green";
    }
    // 判断蓝色
    else if(blue > 150 && red < 100 && green < 100)
    {
        color_index = color_blue;
        color_name = "Blue";
    }
    // 判断黄色
    else if(red > 150 && green > 150 && blue < 100)
    {
        color_index = color_yellow;
        color_name = "Yellow";
    }
    // 判断紫色
    else if(red > 150 && blue > 150 && green < 100)
    {
        color_index = color_purple;
        color_name = "Purple";
    }
    // 判断青色
    else if(green > 150 && blue > 150 && red < 100)
    {
        color_index = color_cyan;
        color_name = "Cyan";
    }
    else
    {
        // 默认红色
        color_index = color_red;
        color_name = "Red";
    }

    // 更新UI显示颜色名称
    if(ui_color_label != NULL)
    {
        char buf[32];
        sprintf(buf, "Color: %s", color_name);
        lv_label_set_text(ui_color_label, buf);
    }
    
    // 通过消息队列发送给RGB LED任务
    if(RGB_ColorQueue != NULL)
    {
        RGB_Color_t rgb_color;
        rgb_color.red = red;
        rgb_color.green = green;
        rgb_color.blue = blue;
        
        // 非阻塞发送
        osMessageQueuePut(RGB_ColorQueue, &rgb_color, 0, 0);
        printf("RGB565=0x%04X -> %s (R=%d,G=%d,B=%d)\n", rgb565, color_name, red, green, blue);
    }
}