// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Project

#include "ui.h"
#include "ui_MotorPage.h"
#include "cmsis_os.h"
#include "user_TaskInit.h"

lv_obj_t * ui_MotorPage = NULL;
lv_obj_t * ui_Arc1 = NULL;
static lv_obj_t * ui_Label3 = NULL;
static lv_obj_t * ui_speed_label = NULL;

static int32_t g_motor_speed_percent = 0;  // 保存上次的速度值
// event funtions
static void motor_arc_event_cb(lv_event_t * e);
/////////////////// Page Manager ////////////////////
Page_t Page_Motor = {
    .init = ui_MotorPage_screen_init,
    .deinit = ui_MotorPage_screen_destroy,
    .page = NULL
};
// build funtions

void ui_MotorPage_screen_init(void)
{
    ui_MotorPage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MotorPage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Arc1 = lv_arc_create(ui_MotorPage);
    lv_obj_set_width(ui_Arc1, 150);
    lv_obj_set_height(ui_Arc1, 150);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    //lv_arc_set_value(ui_Arc1, 50);

    // 设置Arc范围：0-100，对应0%-100%占空比
    lv_arc_set_range(ui_Arc1, 0, 100);
    //lv_arc_set_value(ui_Arc1, 0);
    
    // 设置Arc模式：从0开始
    lv_arc_set_mode(ui_Arc1, LV_ARC_MODE_NORMAL);

    lv_arc_set_value(ui_Arc1, g_motor_speed_percent);
    
    // 添加事件回调：值变化时触发
    lv_obj_add_event_cb(ui_Arc1, motor_arc_event_cb, LV_EVENT_VALUE_CHANGED, NULL);

    ui_Label3 = lv_label_create(ui_MotorPage);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, -100);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Motor Setting");

     // 添加显示当前速度的标签
    ui_speed_label = lv_label_create(ui_MotorPage);
    lv_obj_set_width(ui_speed_label, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_speed_label, LV_SIZE_CONTENT);
    lv_obj_set_x(ui_speed_label, 0);
    lv_obj_set_y(ui_speed_label, 80);
    lv_obj_set_align(ui_speed_label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_speed_label, "Speed: 0%");

    Page_Motor.page = ui_MotorPage;

}

void ui_MotorPage_screen_destroy(void)
{
    //if(ui_MotorPage) lv_obj_del(ui_MotorPage);

    if(ui_Arc1 != NULL)
    {
        g_motor_speed_percent = lv_arc_get_value(ui_Arc1);
    }

    // NULL screen variables
    ui_MotorPage = NULL;
    ui_MotorPage = NULL;
    ui_Arc1 = NULL;
    ui_Label3 = NULL;

}

static void motor_arc_event_cb(lv_event_t * e)
{
    lv_obj_t * arc = lv_event_get_target(e);
    int32_t speed_percent = lv_arc_get_value(arc);  // 获取Arc的值 0-100

     g_motor_speed_percent = speed_percent;
    
    // 更新显示标签
    if(ui_speed_label != NULL)
    {
        char buf[32];
        sprintf(buf, "Speed: %ld%%", speed_percent);
        lv_label_set_text(ui_speed_label, buf);
    }

     // 通过消息队列发送给电机控制任务
    if(Motor_SpeedQueue != NULL)
    {
        // 非阻塞发送（队列满则丢弃旧消息，只保留最新值）
        osMessageQueuePut(Motor_SpeedQueue, &speed_percent, 0, 0);
        printf("Motor speed set to: %ld%%\n", speed_percent);
    }
}
