// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: MeunProject

#include "ui.h"
#include "ui_helpers.h"
#include "ui_MeunPage.h"
#include "ui_AboutPage.h"
#include "ui_HomePage.h"
#include "ui_LightPage.h"
#include "ui_CalendarPage.h"
#include "ui_MotorPage.h"

lv_obj_t * ui_MeunPage = NULL;

Page_t Page_Menu = {
    .init = ui_MeunPage_screen_init,
    .deinit = ui_MeunPage_screen_destroy,
    .page = NULL
};

lv_obj_t * ui_MotorButton;

lv_obj_t * ui_MotorPanel = NULL;
lv_obj_t * ui_MotorButton = NULL;
lv_obj_t * ui_MotorLabel1 = NULL;
lv_obj_t * ui_MotorLabel2 = NULL;
lv_obj_t * ui_LightPanel = NULL;
lv_obj_t * ui_LightButton = NULL;
lv_obj_t * ui_LightLabel1 = NULL;
lv_obj_t * ui_LightLabel2 = NULL;
lv_obj_t * ui_CalenderPanel = NULL;
lv_obj_t * ui_CalenderButton = NULL;
lv_obj_t * ui_CalenderLabel1 = NULL;
lv_obj_t * ui_CalenderLabel2 = NULL;
lv_obj_t * ui_AboutPanel = NULL;
lv_obj_t * ui_AboutButton = NULL;
lv_obj_t * ui_AboutLabel1 = NULL;
lv_obj_t * ui_AboutLabel2 = NULL;

//scroll y
static int16_t ui_MenuScrollY = 0;

// event funtions
void ui_event_MeunPage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code ==  LV_EVENT_GESTURE) 
    {
        if(lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT)
        {
            Page_Back();
        }
        if(event_code == LV_EVENT_SCROLL_END)
        {
            ui_MenuScrollY = lv_obj_get_scroll_y(ui_MeunPage);
        }
    }
}

void ui_event_AboutPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code ==  LV_EVENT_CLICKED) 
    {
        #if ABOUT_PAGE_EN
            printf("About Panel Clicked!\r\n");  // 添加打印
            Page_Load(&Page_About);
        #else

        #endif
    }
}

void ui_event_LightPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code ==  LV_EVENT_CLICKED) 
    {
        #if LIGHT_PAGE_EN
            Page_Load(&Page_Light);
        #else

        #endif
    }
}

void ui_event_CalenderPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code ==  LV_EVENT_CLICKED) 
    {
        #if CALENDAR_PAGE_EN
            Page_Load(&Page_Calendar);
        #else

        #endif
    }
}

void ui_event_MotorPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code ==  LV_EVENT_CLICKED) 
    {
        #if MOTOR_PAGE_EN
            Page_Load(&Page_Motor);
        #else

        #endif
    }
}
// build funtions

void ui_MeunPage_screen_init(void)
{
    ui_MeunPage = lv_obj_create(NULL);

    lv_obj_set_style_bg_color(ui_MeunPage, lv_color_hex(0x000000), LV_PART_MAIN);
lv_obj_set_style_bg_opa(ui_MeunPage, 255, LV_PART_MAIN);
    lv_obj_set_scroll_dir(ui_MeunPage,LV_DIR_VER);  //设置滚动方向为垂直
    lv_obj_set_scrollbar_mode(ui_MeunPage, LV_SCROLLBAR_MODE_ACTIVE);  //设置滚动条模式为拖动时才显示

    ui_MotorPanel = lv_obj_create(ui_MeunPage);
    lv_obj_set_width(ui_MotorPanel, 320);
    lv_obj_set_height(ui_MotorPanel, 70);
    lv_obj_set_x(ui_MotorPanel, 0);
    lv_obj_set_y(ui_MotorPanel, -80);
    lv_obj_set_align(ui_MotorPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MotorPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MotorPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MotorPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_MotorPanel, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_color(ui_MotorPanel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_MotorPanel, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_MotorButton = lv_btn_create(ui_MeunPage);
    lv_obj_set_width(ui_MotorButton, 40);
    lv_obj_set_height(ui_MotorButton, 40);
    lv_obj_set_x(ui_MotorButton, 20);
    lv_obj_set_y(ui_MotorButton, -80);
    lv_obj_set_align(ui_MotorButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_MotorButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MotorButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MotorButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MotorButton, lv_color_hex(0xFF8080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MotorButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorLabel1 = lv_label_create(ui_MeunPage);
    lv_obj_set_width(ui_MotorLabel1, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_MotorLabel1, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_MotorLabel1, 80);
    lv_obj_set_y(ui_MotorLabel1, -80);
    lv_obj_set_align(ui_MotorLabel1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_MotorLabel1, "风扇");
    lv_obj_set_style_text_font(ui_MotorLabel1, &ui_font_zhongyuan30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotorLabel2 = lv_label_create(ui_MeunPage);
    lv_obj_set_width(ui_MotorLabel2, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_MotorLabel2, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_MotorLabel2, 25);
    lv_obj_set_y(ui_MotorLabel2, -80);
    lv_obj_set_align(ui_MotorLabel2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_MotorLabel2, "\xEE\x98\xA3");
    lv_obj_set_style_text_font(ui_MotorLabel2, &ui_font_iconfont31, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightPanel = lv_obj_create(ui_MeunPage);
    lv_obj_set_width(ui_LightPanel, 320);
    lv_obj_set_height(ui_LightPanel, 70);
    lv_obj_set_x(ui_LightPanel, 0);
    lv_obj_set_y(ui_LightPanel, -5);
    lv_obj_set_align(ui_LightPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LightPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LightPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LightPanel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_LightPanel, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_LightButton = lv_btn_create(ui_MeunPage);
    lv_obj_set_width(ui_LightButton, 40);
    lv_obj_set_height(ui_LightButton, 40);
    lv_obj_set_x(ui_LightButton, 20);
    lv_obj_set_y(ui_LightButton, -5);
    lv_obj_set_align(ui_LightButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_LightButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_LightButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LightButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LightButton, lv_color_hex(0xDC80E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightLabel1 = lv_label_create(ui_MeunPage);
    lv_obj_set_width(ui_LightLabel1, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_LightLabel1, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_LightLabel1, 80);
    lv_obj_set_y(ui_LightLabel1, -5);
    lv_obj_set_align(ui_LightLabel1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LightLabel1, "灯光");
    lv_obj_set_style_text_font(ui_LightLabel1, &ui_font_zhongyuan30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightLabel2 = lv_label_create(ui_MeunPage);
    lv_obj_set_width(ui_LightLabel2, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_LightLabel2, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_LightLabel2, 25);
    lv_obj_set_y(ui_LightLabel2, -5);
    lv_obj_set_align(ui_LightLabel2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LightLabel2, "\xEE\x98\x8F");
    lv_obj_set_style_text_font(ui_LightLabel2, &ui_font_iconfont10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalenderPanel = lv_obj_create(ui_MeunPage);
    lv_obj_set_width(ui_CalenderPanel, 320);
    lv_obj_set_height(ui_CalenderPanel, 70);
    lv_obj_set_x(ui_CalenderPanel, 0);
    lv_obj_set_y(ui_CalenderPanel, 70);
    lv_obj_set_align(ui_CalenderPanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CalenderPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CalenderPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CalenderPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CalenderPanel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_CalenderPanel, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_CalenderButton = lv_btn_create(ui_MeunPage);
    lv_obj_set_width(ui_CalenderButton, 40);
    lv_obj_set_height(ui_CalenderButton, 40);
    lv_obj_set_x(ui_CalenderButton, 20);
    lv_obj_set_y(ui_CalenderButton, 70);
    lv_obj_set_align(ui_CalenderButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_CalenderButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CalenderButton, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CalenderButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CalenderButton, lv_color_hex(0xC07010), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CalenderButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalenderLabel1 = lv_label_create(ui_MeunPage);
    lv_obj_set_width(ui_CalenderLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalenderLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalenderLabel1, 80);
    lv_obj_set_y(ui_CalenderLabel1, 70);
    lv_obj_set_align(ui_CalenderLabel1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_CalenderLabel1, "日历");
    lv_obj_set_style_text_font(ui_CalenderLabel1, &ui_font_zhongyuan30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalenderLabel2 = lv_label_create(ui_MeunPage);
    lv_obj_set_width(ui_CalenderLabel2, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_CalenderLabel2, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_CalenderLabel2, 25);
    lv_obj_set_y(ui_CalenderLabel2, 70);
    lv_obj_set_align(ui_CalenderLabel2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_CalenderLabel2, "\xEE\x98\x80");
    lv_obj_set_style_text_font(ui_CalenderLabel2, &ui_font_iconfont20, LV_PART_MAIN | LV_STATE_DEFAULT);

    
    ui_AboutPanel = lv_obj_create(ui_MeunPage);
    lv_obj_set_width(ui_AboutPanel, 320);
    lv_obj_set_height(ui_AboutPanel, 70);
    lv_obj_set_x(ui_AboutPanel, 0);
    lv_obj_set_y(ui_AboutPanel, 145);
    lv_obj_set_align(ui_AboutPanel, LV_ALIGN_CENTER);
    //lv_obj_clear_flag(ui_AboutPanel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_AboutPanel, LV_OBJ_FLAG_CLICKABLE);      // 添加可点击
lv_obj_clear_flag(ui_AboutPanel, LV_OBJ_FLAG_SCROLLABLE);   // 不可滚动
    lv_obj_set_style_bg_color(ui_AboutPanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AboutPanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AboutPanel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_AboutPanel, 100, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_AboutButton = lv_btn_create(ui_MeunPage);
    lv_obj_set_width(ui_AboutButton, 40);
    lv_obj_set_height(ui_AboutButton, 40);
    lv_obj_set_x(ui_AboutButton, 20);
    lv_obj_set_y(ui_AboutButton, 145);
    lv_obj_set_align(ui_AboutButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_AboutButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AboutButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AboutButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_AboutButton, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AboutButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AboutLabel1 = lv_label_create(ui_MeunPage);
    lv_obj_set_width(ui_AboutLabel1, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_AboutLabel1, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_AboutLabel1, 80);
    lv_obj_set_y(ui_AboutLabel1, 145);
    lv_obj_set_align(ui_AboutLabel1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_AboutLabel1, "关于");
    lv_obj_set_style_text_font(ui_AboutLabel1, &ui_font_zhongyuan30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AboutLabel2 = lv_label_create(ui_MeunPage);
    lv_obj_set_width(ui_AboutLabel2, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_height(ui_AboutLabel2, LV_SIZE_CONTENT);    /// 40
    lv_obj_set_x(ui_AboutLabel2, 25);
    lv_obj_set_y(ui_AboutLabel2, 145);
    lv_obj_set_align(ui_AboutLabel2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_AboutLabel2, "\xEE\xA3\xA5");
    lv_obj_set_style_text_font(ui_AboutLabel2, &ui_font_iconfont40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MeunPage = ui_MeunPage;
    ui_MotorButton = ui_MotorButton;

    lv_obj_add_event_cb(ui_MeunPage, ui_event_MeunPage, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_AboutPanel, ui_event_AboutPanel, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_LightPanel, ui_event_LightPanel, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_CalenderPanel, ui_event_CalenderPanel, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_MotorPanel, ui_event_MotorPanel, LV_EVENT_CLICKED, NULL);

    Page_Menu.page = ui_MeunPage;
}

void ui_MeunPage_screen_destroy(void)
{
    //if(ui_MeunPage) lv_obj_del(ui_MeunPage);

    // NULL screen variables
    ui_MeunPage = NULL;
    Page_Menu.page = NULL;
    ui_MotorPanel = NULL;
    ui_MotorButton = NULL;
    ui_MotorButton = NULL;
    ui_MotorLabel1 = NULL;
    ui_MotorLabel2 = NULL;
    ui_LightPanel = NULL;
    ui_LightButton = NULL;
    ui_LightLabel1 = NULL;
    ui_LightLabel2 = NULL;
    ui_CalenderPanel = NULL;
    ui_CalenderButton = NULL;
    ui_CalenderLabel1 = NULL;
    ui_CalenderLabel2 = NULL;
    ui_AboutPanel = NULL;
    ui_AboutButton = NULL;
    ui_AboutLabel1 = NULL;
    ui_AboutLabel2 = NULL;

}
